version: '3'

services:
  py-nplus1loader-postgres-test:
    image: postgres:9
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_nplus1loader
