version: '3'

services:
  py-nplus1loader-postgres-test:
    image: postgres:latest
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_nplus1loader

  py-nplus1loader-mysql-test:
    image: mysql:latest
    restart: always
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'test_nplus1loader'
